# Generated by Django 2.1 on 2019-08-02 03:06

import User.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id_assigned', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('C', 'Ortopedista'), ('A', 'Analista de requerimientos'), ('I', 'Ingenieria inversa'), ('D', 'Diseñador'), ('P', 'P rapido'), ('G', 'Gestor de conocimiento'), ('M', 'Metodologia')], max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigneds', to='User.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id_case', models.AutoField(help_text='ID del caso', primary_key=True, serialize=False)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('ips', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=10)),
                ('state', models.CharField(choices=[('1', 'cotizacion'), ('2', 'ejecucion'), ('3', 'suspencion'), ('4', 'finalizacion')], default='1', max_length=1)),
                ('age', models.CharField(max_length=3)),
                ('metallic_artifact', models.BooleanField(default=False)),
                ('deadline', models.CharField(max_length=3)),
                ('diagnostic', models.TextField()),
                ('process_q', models.TextField()),
                ('etiology', models.CharField(choices=[('c', 'congenito'), ('o', 'oncologico'), ('t', 'traumatico')], max_length=10)),
                ('zone', models.CharField(choices=[('s', 'superior'), ('m', 'media'), ('i', 'inferior'), ('c', 'craneo')], max_length=10)),
                ('evolution', models.CharField(choices=[('a', 'agudo'), ('s', 'subagudo'), ('c', 'cronico')], max_length=10)),
                ('screw', models.CharField(max_length=6, null=True)),
                ('recession', models.BooleanField(default=False)),
                ('margen_recession', models.CharField(max_length=6, null=True)),
                ('fastenings', models.CharField(max_length=2, null=True)),
                ('incisions', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CasePackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CasePackageActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='User.Activity')),
                ('case_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_package', to='User.CasePackage')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_card', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField()),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='User.Package')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_card', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('C', 'Ortopedista'), ('A', 'Analista de requerimientos'), ('I', 'Ingenieria inversa'), ('D', 'Diseñador'), ('P', 'P rapido'), ('G', 'Gestor de conocimiento'), ('M', 'Metodologia')], max_length=1)),
                ('specialty', models.TextField()),
                ('hability', models.TextField()),
                ('email', models.CharField(max_length=60, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('activitys', models.ManyToManyField(related_name='users', through='User.Assigned', to='User.Activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', User.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='casepackage',
            name='activity',
            field=models.ManyToManyField(related_name='case_packages', through='User.CasePackageActivity', to='User.Activity'),
        ),
        migrations.AddField(
            model_name='casepackage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_packages', to='User.Case'),
        ),
        migrations.AddField(
            model_name='casepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_packages', to='User.Package'),
        ),
        migrations.AddField(
            model_name='case',
            name='packages',
            field=models.ManyToManyField(related_name='cases', through='User.CasePackage', to='User.Package'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='User.Patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigneds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='case_package',
            field=models.ManyToManyField(related_name='activitys', through='User.CasePackageActivity', to='User.CasePackage'),
        ),
        migrations.AlterUniqueTogether(
            name='casepackageactivity',
            unique_together={('activity', 'case_package')},
        ),
        migrations.AlterUniqueTogether(
            name='casepackage',
            unique_together={('case', 'package')},
        ),
        migrations.AlterUniqueTogether(
            name='assigned',
            unique_together={('user', 'activity')},
        ),
    ]
