# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id_case', models.AutoField(help_text='ID del caso', primary_key=True, serialize=False)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('ips', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('metallic_artifact', models.BooleanField(default=False)),
                ('deadline', models.CharField(max_length=3)),
                ('diagnostic', models.TextField()),
                ('process_q', models.TextField()),
                ('etiology', models.CharField(choices=[('c', 'congenito'), ('o', 'oncologico'), ('t', 'traumatico')], max_length=10)),
                ('zone', models.CharField(choices=[('s', 'superior'), ('m', 'media'), ('i', 'inferior'), ('c', 'craneo')], max_length=10)),
                ('evolution', models.CharField(choices=[('a', 'agudo'), ('s', 'subagudo'), ('c', 'cronico')], max_length=10)),
                ('screw', models.CharField(max_length=6, null=True)),
                ('recession', models.BooleanField(default=False)),
                ('margen_recession', models.CharField(max_length=6, null=True)),
                ('fastenings', models.CharField(max_length=2, null=True)),
                ('incisions', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('id_card', models.CharField(max_length=15)),
                ('birth', models.DateField()),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('specialty', models.TextField()),
                ('hability', models.TextField()),
                ('email', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
