# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 20:51
from __future__ import unicode_literals

import User.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id_case', models.AutoField(help_text='ID del caso', primary_key=True, serialize=False)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('ips', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('metallic_artifact', models.BooleanField(default=False)),
                ('deadline', models.CharField(max_length=3)),
                ('diagnostic', models.TextField()),
                ('process_q', models.TextField()),
                ('etiology', models.CharField(choices=[('c', 'congenito'), ('o', 'oncologico'), ('t', 'traumatico')], max_length=10)),
                ('zone', models.CharField(choices=[('s', 'superior'), ('m', 'media'), ('i', 'inferior'), ('c', 'craneo')], max_length=10)),
                ('evolution', models.CharField(choices=[('a', 'agudo'), ('s', 'subagudo'), ('c', 'cronico')], max_length=10)),
                ('screw', models.CharField(max_length=6, null=True)),
                ('recession', models.BooleanField(default=False)),
                ('margen_recession', models.CharField(max_length=6, null=True)),
                ('fastenings', models.CharField(max_length=2, null=True)),
                ('incisions', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_card', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField()),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('fk_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Package')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_card', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=1)),
                ('specialty', models.TextField()),
                ('hability', models.TextField()),
                ('email', models.CharField(max_length=60, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', User.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='fk_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Package'),
        ),
        migrations.AddField(
            model_name='case',
            name='fk_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
