# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 22:16
from __future__ import unicode_literals

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    names = [
        'Planeamiento pre-quirúrgico',
        'Prototipo Pre-Quirurjico',
        'Prototipo Guía Corte',
        'Biomodelo Virtual',
        'Prototipo Post-Quirurjico',
        'Molde Obtención Injertos',
        'Diseño de Implante',
    ]

    Package = apps.get_model('User', 'Package')

    for name_ in names:
        package = Package(name=name_)
        package.save()

class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(combine_names),
    ]
