# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190507_0732'),
        ('User', '0003_auto_20190507_0732'),
    ]

    operations = [
    ]
