# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_merge_20190507_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Ortopedista'), ('A', 'Analista de requerimientos'), ('I', 'Ingenieria inversa'), ('D', 'Diseñador'), ('P', 'P rapido'), ('G', 'Gestor de conocimiento'), ('M', 'Metodologia')], max_length=1),
        ),
    ]
