# Generated by Django 2.1 on 2019-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190723_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepackage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
