# Generated by Django 2.1 on 2019-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190802_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
