# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190508_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('1', 'cotizacion'), ('2', 'ejecucion'), ('3', 'suspencion'), ('4', 'finalizacion')], default=1, max_length=1),
        ),
    ]
