# Generated by Django 2.1 on 2019-07-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190728_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casepackage',
            unique_together={('case', 'package')},
        ),
    ]
